#include "Keys.h"

// Define all exported constant integers.

ENGINE_API const int KEY_UNKNOWN = GLFW_KEY_UNKNOWN;
ENGINE_API const int KEY_BACKSPACE = GLFW_KEY_BACKSPACE;
ENGINE_API const int KEY_TAB = GLFW_KEY_TAB;
ENGINE_API const int KEY_RETURN = GLFW_KEY_ENTER;
ENGINE_API const int KEY_PAUSE = GLFW_KEY_PAUSE;
ENGINE_API const int KEY_ESCAPE = GLFW_KEY_ESCAPE;
ENGINE_API const int KEY_SPACE = GLFW_KEY_SPACE;
ENGINE_API const int KEY_COMMA = GLFW_KEY_COMMA;
ENGINE_API const int KEY_MINUS = GLFW_KEY_MINUS;
ENGINE_API const int KEY_PERIOD = GLFW_KEY_PERIOD;
ENGINE_API const int KEY_SLASH = GLFW_KEY_SLASH;

ENGINE_API const int KEY_0 = GLFW_KEY_0;
ENGINE_API const int KEY_1 = GLFW_KEY_1;
ENGINE_API const int KEY_2 = GLFW_KEY_2;
ENGINE_API const int KEY_3 = GLFW_KEY_3;
ENGINE_API const int KEY_4 = GLFW_KEY_4;
ENGINE_API const int KEY_5 = GLFW_KEY_5;
ENGINE_API const int KEY_6 = GLFW_KEY_6;
ENGINE_API const int KEY_7 = GLFW_KEY_7;
ENGINE_API const int KEY_8 = GLFW_KEY_8;
ENGINE_API const int KEY_9 = GLFW_KEY_9;

ENGINE_API const int KEY_SEMICOLON = GLFW_KEY_SEMICOLON;
ENGINE_API const int KEY_EQUALS = GLFW_KEY_EQUAL;
ENGINE_API const int KEY_LEFTBRACKET = GLFW_KEY_LEFT_BRACKET;
ENGINE_API const int KEY_BACKSLASH = GLFW_KEY_BACKSLASH;
ENGINE_API const int KEY_RIGHTBRACKET = GLFW_KEY_RIGHT_BRACKET;

ENGINE_API const int KEY_A = GLFW_KEY_A;
ENGINE_API const int KEY_B = GLFW_KEY_B;
ENGINE_API const int KEY_C = GLFW_KEY_C;
ENGINE_API const int KEY_D = GLFW_KEY_D;
ENGINE_API const int KEY_E = GLFW_KEY_E;
ENGINE_API const int KEY_F = GLFW_KEY_F;
ENGINE_API const int KEY_G = GLFW_KEY_G;
ENGINE_API const int KEY_H = GLFW_KEY_H;
ENGINE_API const int KEY_I = GLFW_KEY_I;
ENGINE_API const int KEY_J = GLFW_KEY_J;
ENGINE_API const int KEY_K = GLFW_KEY_K;
ENGINE_API const int KEY_L = GLFW_KEY_L;
ENGINE_API const int KEY_M = GLFW_KEY_M;
ENGINE_API const int KEY_N = GLFW_KEY_N;
ENGINE_API const int KEY_O = GLFW_KEY_O;
ENGINE_API const int KEY_P = GLFW_KEY_P;
ENGINE_API const int KEY_Q = GLFW_KEY_Q;
ENGINE_API const int KEY_R = GLFW_KEY_R;
ENGINE_API const int KEY_S = GLFW_KEY_S;
ENGINE_API const int KEY_T = GLFW_KEY_T;
ENGINE_API const int KEY_U = GLFW_KEY_U;
ENGINE_API const int KEY_V = GLFW_KEY_V;
ENGINE_API const int KEY_W = GLFW_KEY_W;
ENGINE_API const int KEY_X = GLFW_KEY_X;
ENGINE_API const int KEY_Y = GLFW_KEY_Y;
ENGINE_API const int KEY_Z = GLFW_KEY_Z;

ENGINE_API const int KEY_DELETE = GLFW_KEY_DELETE;
ENGINE_API const int KEY_CAPSLOCK = GLFW_KEY_CAPS_LOCK;

ENGINE_API const int KEY_F1 = GLFW_KEY_F1;
ENGINE_API const int KEY_F2 = GLFW_KEY_F2;
ENGINE_API const int KEY_F3 = GLFW_KEY_F3;
ENGINE_API const int KEY_F4 = GLFW_KEY_F4;
ENGINE_API const int KEY_F5 = GLFW_KEY_F5;
ENGINE_API const int KEY_F6 = GLFW_KEY_F6;
ENGINE_API const int KEY_F7 = GLFW_KEY_F7;
ENGINE_API const int KEY_F8 = GLFW_KEY_F8;
ENGINE_API const int KEY_F9 = GLFW_KEY_F9;
ENGINE_API const int KEY_F10 = GLFW_KEY_F10;
ENGINE_API const int KEY_F11 = GLFW_KEY_F11;
ENGINE_API const int KEY_F12 = GLFW_KEY_F12;

ENGINE_API const int KEY_INSERT = GLFW_KEY_INSERT;
ENGINE_API const int KEY_HOME = GLFW_KEY_HOME;
ENGINE_API const int KEY_PAGEUP = GLFW_KEY_PAGE_UP;
ENGINE_API const int KEY_END = GLFW_KEY_END;
ENGINE_API const int KEY_PAGEDOWN = GLFW_KEY_PAGE_DOWN;
ENGINE_API const int KEY_RIGHT = GLFW_KEY_RIGHT;
ENGINE_API const int KEY_LEFT = GLFW_KEY_LEFT;
ENGINE_API const int KEY_DOWN = GLFW_KEY_DOWN;
ENGINE_API const int KEY_UP = GLFW_KEY_UP;

ENGINE_API const int KEY_NUMLOCK = GLFW_KEY_NUM_LOCK;
ENGINE_API const int KEY_KP_DIVIDE = GLFW_KEY_KP_DIVIDE;
ENGINE_API const int KEY_KP_MULTIPLY = GLFW_KEY_KP_MULTIPLY;
ENGINE_API const int KEY_KP_MINUS = GLFW_KEY_KP_SUBTRACT;
ENGINE_API const int KEY_KP_PLUS = GLFW_KEY_KP_ADD;
ENGINE_API const int KEY_KP_ENTER = GLFW_KEY_KP_ENTER;
ENGINE_API const int KEY_KP1 = GLFW_KEY_KP_1;
ENGINE_API const int KEY_KP2 = GLFW_KEY_KP_2;
ENGINE_API const int KEY_KP3 = GLFW_KEY_KP_3;
ENGINE_API const int KEY_KP4 = GLFW_KEY_KP_4;
ENGINE_API const int KEY_KP5 = GLFW_KEY_KP_5;
ENGINE_API const int KEY_KP6 = GLFW_KEY_KP_6;
ENGINE_API const int KEY_KP7 = GLFW_KEY_KP_7;
ENGINE_API const int KEY_KP8 = GLFW_KEY_KP_8;
ENGINE_API const int KEY_KP9 = GLFW_KEY_KP_9;
ENGINE_API const int KEY_KP0 = GLFW_KEY_KP_0;
ENGINE_API const int KEY_KP_PERIOD = GLFW_KEY_KP_DECIMAL;

ENGINE_API const int KEY_LCTRL = GLFW_KEY_LEFT_CONTROL;
ENGINE_API const int KEY_LSHIFT = GLFW_KEY_LEFT_SHIFT;
ENGINE_API const int KEY_LALT = GLFW_KEY_LEFT_ALT;
ENGINE_API const int KEY_RCTRL = GLFW_KEY_RIGHT_CONTROL;
ENGINE_API const int KEY_RSHIFT = GLFW_KEY_RIGHT_SHIFT;
ENGINE_API const int KEY_RALT = GLFW_KEY_RIGHT_ALT;
