#include "MouseButtons.h"


ENGINE_API const int MOUSE_UNKNOWN = -1;
ENGINE_API const int MOUSE_LEFT = GLFW_MOUSE_BUTTON_LEFT;	   // 0
ENGINE_API const int MOUSE_MIDDLE = GLFW_MOUSE_BUTTON_MIDDLE; // 2
ENGINE_API const int MOUSE_RIGHT = GLFW_MOUSE_BUTTON_RIGHT;   // 1

